### ISSUE TITLE
Use standard function names

### ISSUE THREAD

**Issue by creack** [cdr/flog#5]
The standard go way to deal with format function is to have a `f` suffix. This is used by tools like `go vet` to detect errors and typos.

A simple fix would be to add `f` functions calling the regular one.

Example of the problem:

```go
var local, remote string
flog.Info("doing initial sync (%s -> %d)", local, remote)
```
```shell
$> go vet -printf.funcs go.coder.com/flog.Info ./...
# No result.
```

While having standard `Infof` would result in:

```go
var local, remote string
flog.Infof("doing initial sync (%s -> %d)", local, remote)
```
```shell
$> go vet -printf.funcs go.coder.com/flog.Infof ./...
main.go:25:2: Errorf format %d has arg remote of wrong type string
```

**Comment by creack** [comment]
cc @nhooyr

**Comment by nhooyr** [comment]
I agree, I blame @ammario

**Comment by ammario** [comment]
👍 and @nhooyr designed this API

**Comment by nhooyr** [comment]
> 👍 and @nhooyr designed this API

straight lies
